/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiralabra;
import org.junit.Test;
import static org.junit.Assert.*;

public class SovellusTest {
    @Test public void SovellusKaynnistyy() {
        
    }
}
